apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-thiago
  description: A collection of all Backstage example entities, except users, groups, and templates
spec:
  targets:
    - ./apis/api.yaml
    - ./apis/api2.yaml
    - ./apis/api3.yaml
    - ./apis/api5.yaml
    - ./apis/api10.yaml
    - ./apis/api50.yaml
