apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: thiago-teste
  description: Thiago Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Thiago
      icon: user
  annotations:
    oculus.stone.tech/configured: 'true'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
